[project]
name = "django-svelte"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "django>=5.2",
    "django-vite>=3.1.0",
    "whitenoise>=6.9.0",
]
